---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# epiDeaths

<!-- badges: start -->
<!-- badges: end -->

epiDeaths is an R package designed to provide functions for calculating mortality indicators. These include geometric interpolation between two periods and projections for future years, as described in the textbook by Laurenti, Mello Jorge, Lebrão and Gotlieb (2005), the standardised mortality ratio (Bruce, Pope and Stanistreet, 2018), the age-adjusted mortality rate (direct standardisation), years of potential life lost (Gardner and Sanborn, 1990; Ma, Ward, Siegel and Jemal, 2015), and age-standardised years of potential life lost (Silva Filho et al., 2024). Confidence intervals for the standardised mortality ratio are obtained according to Vandenbroucke (1982) and Ulm (1990). The function also includes a function that produces a graph similar to an age pyramid.

## Installation

You can install the epiDeaths package from CRAN with:

``` r
# install.packages("epiDeaths")
```
